from app.services.auth_service import (
    auth_admin,
    auth_user,
    change_password,
    handle_google_login,
    register_user,
    update_profile,
)
from app.services.chat_service import (
    count_unread,
    create_private_conversation,
    get_conversation_messages,
    get_user_conversations,
    search_messages,
)
from app.services.course_service import (
    activate_course,
    create_course,
    delete_course,
    get_all_active_courses,
    get_course_detail,
    get_teacher_courses,
    update_course,
)
from app.services.forum_service import (
    accept_answer,
    add_answer,
    create_question,
    get_all_categories,
    get_forum_detail,
    get_forum_posts,
    reply_comment,
    vote_comment,
    vote_post,
)
from app.services.learning_service import (
    enroll_course,
    get_learn_context,
    get_my_learning,
    mark_lesson_completed,
)
from app.services.payment_service import (
    checkout_course,
    get_my_payments,
    process_ipn,
    process_return,
)
from app.services.teacher_service import get_latest_application, submit_teacher_application
from app.services.test_service import (
    calculate_remaining_time,
    get_course_by_teacher,
    get_test_context,
    get_test_for_teacher,
    submit_test,
    sync_questions,
)
from app.services.upload_service import upload_file

__all__ = [
    "upload_file",
    "register_user",
    "auth_user",
    "auth_admin",
    "handle_google_login",
    "update_profile",
    "change_password",
    "submit_teacher_application",
    "get_latest_application",
    "get_all_active_courses",
    "get_teacher_courses",
    "get_course_detail",
    "create_course",
    "update_course",
    "delete_course",
    "activate_course",
    "get_my_learning",
    "enroll_course",
    "get_learn_context",
    "mark_lesson_completed",
    "get_test_context",
    "calculate_remaining_time",
    "submit_test",
    "sync_questions",
    "get_test_for_teacher",
    "get_course_by_teacher",
    "get_forum_posts",
    "get_forum_detail",
    "create_question",
    "get_all_categories",
    "add_answer",
    "accept_answer",
    "vote_post",
    "vote_comment",
    "reply_comment",
    "get_user_conversations",
    "get_conversation_messages",
    "create_private_conversation",
    "search_messages",
    "count_unread",
    "checkout_course",
    "process_ipn",
    "process_return",
    "get_my_payments",
]
