"""Add price column to Course model

Revision ID: 35a90f9c8f09
Revises: 
Create Date: 2026-07-29 21:35:10.839234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35a90f9c8f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('comment')
    op.drop_table('lesson')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_id'))

    op.drop_table('teacher')
    op.drop_table('video_content')
    op.drop_table('reaction_post')
    op.drop_table('chapter')
    op.drop_table('course_category')
    op.drop_table('course_outcome')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('user')
    op.drop_table('teacher_application')
    op.drop_table('doc_content')
    op.drop_table('reaction_comment')
    op.drop_table('post_cate')
    op.drop_table('course')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('view_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_solved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['post_cate.id'], name=op.f('post_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('post_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('is_sale', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', mysql.ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED'), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('course_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_cate',
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote_type', mysql.ENUM('UP', 'DOWN'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('reaction_comment_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('reaction_comment_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_content',
    sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_text', mysql.TEXT(), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('doc_content_ibfk_1')),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('teacher_application',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workplace', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('degree', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bio', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('expertise', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('teach_style', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('linkedin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_card_file', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('degree_file', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('cv_file', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('extra_cert_file', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('video_file', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=False),
    sa.Column('reject_reason', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('teacher_application_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('teacher_application_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('google_sub', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('course_outcome',
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('course_outcome_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_category',
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('course_category_ibfk_2')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('course_category_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'category_id')
    )
    op.create_table('chapter',
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('chapter_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_post',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote_type', mysql.ENUM('UP', 'DOWN'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('reaction_post_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('reaction_post_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_content',
    sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('video_content_ibfk_1')),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('teacher',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('teacher_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    op.create_table('lesson',
    sa.Column('type', mysql.ENUM('VIDEO', 'NONE', 'DOCUMENT'), nullable=False),
    sa.Column('chapter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], name=op.f('lesson_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('is_accepted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], name=op.f('comment_ibfk_3')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('comment_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('comment_ibfk_2')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('updated_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
