"""optimize db and delete N+1 query

Revision ID: 495adc0081d7
Revises: b28a5bb370b2
Create Date: 2026-08-02 23:53:27.827246

"""
from alembic import o
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '495adc0081d7'
down_revision = 'b28a5bb370b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answer_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'comment', ['parent_comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_category_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_outcome_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doc_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('doc_content_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('uix_progress_per_attempt'))
        batch_op.create_unique_constraint('uix_progress_per_enrollment_lesson', ['enrollment_id', 'lesson_id'])
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('enrollment_created_date')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reaction_comment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reaction_post_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=False))
        batch_op.alter_column('score_value',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_unique_constraint('uix_score_per_attempt', ['enrollment_id', 'test_id', 'attempt_number'])
        batch_op.drop_constraint(batch_op.f('score_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('enrollment_created_date')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_application_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('test_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['google_sub'])

    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('video_content_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_content_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('test_ibfk_2'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('test_ibfk_1'), 'chapter', ['chapter_id'], ['id'])

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_application_ibfk_2'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_ibfk_1'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_created_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('score_ibfk_1'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('score_ibfk_2'), 'test', ['test_id'], ['id'])
        batch_op.drop_constraint('uix_score_per_attempt', type_='unique')
        batch_op.alter_column('score_value',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('enrollment_id')

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_post_ibfk_1'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_comment_ibfk_1'), 'comment', ['comment_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_ibfk_1'), 'test', ['test_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_1'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_1'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_2'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_created_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_progress_ibfk_1'), 'enrollment', ['enrollment_created_date', 'user_id', 'course_id'], ['created_date', 'user_id', 'course_id'], ondelete='CASCADE')
        batch_op.drop_constraint('uix_progress_per_enrollment_lesson', type_='unique')
        batch_op.create_index(batch_op.f('uix_progress_per_attempt'), ['user_id', 'course_id', 'enrollment_created_date', 'lesson_id'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')
        batch_op.drop_column('name')
        batch_op.drop_column('enrollment_id')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_ibfk_1'), 'chapter', ['chapter_id'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('doc_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('doc_content_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_outcome_ibfk_1'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_category_ibfk_1'), 'category', ['category_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_2'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_3'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_1'), 'comment', ['parent_comment_id'], ['id'])

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_ibfk_1'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answer_ibfk_1'), 'question', ['question_id'], ['id'])

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
