"""optimize db and delete N+1 query

Revision ID: 495adc0081d7
Revises: b28a5bb370b2
Create Date: 2026-08-02 23:53:27.827246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '495adc0081d7'
down_revision = 'b28a5bb370b2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('admin_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answer_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chapter_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_category_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_outcome_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doc_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('doc_content_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    # --- FIX: xoá data test trong 3 bảng liên quan trước khi đổi cấu trúc ---
    # Data hiện tại toàn là data test (đã xác nhận không cần giữ), nên xoá sạch
    # trước khi thêm cột NOT NULL / đổi PRIMARY KEY - né toàn bộ lỗi kiểu
    # "column can't be null" hay phải viết logic backfill phức tạp.
    # Thứ tự xoá: score -> lesson_progress -> enrollment (con trước, cha sau).
    op.execute("DELETE FROM score")
    op.execute("DELETE FROM lesson_progress")
    op.execute("DELETE FROM enrollment")

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        # Thêm cột id thường trước (chưa auto-increment, chưa là key)
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # --- FIX: phần Alembic autogenerate hoàn toàn bỏ sót ---
    # Phải DROP PRIMARY KEY cũ (created_date, user_id, course_id) và
    # ADD PRIMARY KEY mới (id) + MODIFY ... AUTO_INCREMENT trong CÙNG 1 câu
    # ALTER TABLE. MySQL bắt buộc: 1 cột AUTO_INCREMENT phải là 1 key ngay tại
    # thời điểm được khai báo auto_increment - không thể tách thành 2 lệnh
    # alter_column() + create_primary_key() riêng biệt như batch_alter_table
    # thường làm, nên phải dùng raw SQL gộp chung ở đây.
    op.execute(
        """
        ALTER TABLE enrollment
        DROP PRIMARY KEY,
        MODIFY id INT NOT NULL AUTO_INCREMENT,
        ADD PRIMARY KEY (id)
        """
    )

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('uix_progress_per_attempt'))
        batch_op.create_unique_constraint('uix_progress_per_enrollment_lesson', ['enrollment_id', 'lesson_id'])
        batch_op.drop_constraint(batch_op.f('lesson_progress_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('enrollment_created_date')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reaction_comment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reaction_post_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=False))
        batch_op.alter_column('score_value',
                              existing_type=mysql.FLOAT(),
                              type_=sa.DECIMAL(precision=10, scale=2),
                              existing_nullable=False)
        batch_op.create_unique_constraint('uix_score_per_attempt', ['enrollment_id', 'test_id', 'attempt_number'])
        batch_op.drop_constraint(batch_op.f('score_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('score_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('course_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_application_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('test_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['google_sub'])

    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('video_content_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_content_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('test_ibfk_2'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('test_ibfk_1'), 'chapter', ['chapter_id'], ['id'])

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_application_ibfk_2'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_ibfk_1'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('score_ibfk_1'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('score_ibfk_2'), 'test', ['test_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('score_ibfk_3'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('uix_score_per_attempt', type_='unique')
        batch_op.alter_column('score_value',
                              existing_type=sa.DECIMAL(precision=10, scale=2),
                              type_=mysql.FLOAT(),
                              existing_nullable=False)
        batch_op.drop_column('enrollment_id')

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_post_ibfk_1'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_comment_ibfk_1'), 'comment', ['comment_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_ibfk_1'), 'test', ['test_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_ibfk_1'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_1'), 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_2'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('enrollment_created_date', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_progress_per_enrollment_lesson', type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('created_date')
        batch_op.drop_column('name')
        batch_op.drop_column('enrollment_id')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_ibfk_1'), 'chapter', ['chapter_id'], ['id'])

    # --- FIX: đảo ngược việc đổi PRIMARY KEY - cũng phải gộp 1 câu SQL ---
    # Không thể tách drop PK mới + add PK cũ (composite) thành 2 bước riêng
    # nếu id vẫn đang AUTO_INCREMENT, nên bỏ AUTO_INCREMENT trước trong lúc
    # đổi PK trong cùng câu lệnh.
    op.execute(
        """
        ALTER TABLE enrollment
        DROP PRIMARY KEY,
        MODIFY id INT NOT NULL,
        ADD PRIMARY KEY (created_date, user_id, course_id)
        """
    )

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('created_date',
                              existing_type=mysql.DATETIME(),
                              nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_date')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('doc_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('doc_content_ibfk_1'), 'lesson', ['lesson_id'], ['id'])

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_outcome_ibfk_1'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('course_category_ibfk_1'), 'category', ['category_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_1'), 'comment', ['parent_comment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_2'), 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_3'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chapter_ibfk_1'), 'course', ['course_id'], ['id'])

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answer_ibfk_1'), 'question', ['question_id'], ['id'])

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_ibfk_1'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
