"""add pass_score to test

Revision ID: ed7015f28d92
Revises: 5d6731645b34
Create Date: 2026-08-19 02:20:49.080542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7015f28d92'
down_revision = '5d6731645b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_score', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('pass_score')

    # ### end Alembic commands ###
