"""Initial migration

Revision ID: fd9dc4a3d1cb
Revises: 
Create Date: 2026-08-18 21:45:15.527753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd9dc4a3d1cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('activate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=mysql.ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED'),
               nullable=True)

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED'),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('VIDEO', 'NONE', 'DOCUMENT'),
               nullable=True)
        batch_op.alter_column('chapter_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.alter_column('enrollment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('message_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message_reaction', schema=None) as batch_op:
        batch_op.alter_column('emoji',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('message_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('message_reaction_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('request_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED'),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.alter_column('comment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vote_type',
               existing_type=mysql.ENUM('UP', 'DOWN'),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uix_vote_per_user_comment', ['user_id', 'comment_id'])
        batch_op.drop_constraint(batch_op.f('reaction_comment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('vote_type',
               existing_type=mysql.ENUM('UP', 'DOWN'),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uix_vote_per_user_post', ['user_id', 'post_id'])
        batch_op.drop_constraint(batch_op.f('reaction_post_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('enrollment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('score_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('id_card_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('degree_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('cv_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_content', schema=None) as batch_op:
        batch_op.alter_column('video_url',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'),
               nullable=False)
        batch_op.alter_column('cv_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('degree_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('id_card_file',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.alter_column('score_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('enrollment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reaction_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_post_ibfk_2'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('uix_vote_per_user_post', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('vote_type',
               existing_type=mysql.ENUM('UP', 'DOWN'),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reaction_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reaction_comment_ibfk_2'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('uix_vote_per_user_comment', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('vote_type',
               existing_type=mysql.ENUM('UP', 'DOWN'),
               nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED'),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('request_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('message_reaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_reaction_ibfk_2'), 'user', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('message_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('emoji',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_ibfk_2'), 'user', ['sender_id'], ['id'])
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('lesson_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('enrollment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('chapter_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('VIDEO', 'NONE', 'DOCUMENT'),
               nullable=False)

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED'),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('course_outcome', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED'),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('activate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
